# Generated by Django 6.0.4 on 2026-07-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='muscle',
        ),
    ]
