# Generated by Django 6.0.4 on 2026-08-15 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_steps_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.workout'),
        ),
        migrations.AlterField(
            model_name='workoutmedia',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_media', to='api.workout'),
        ),
    ]
