# Generated by Django 5.2.17 on 2026-09-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_equipment_id_alter_musclegroup_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
