# Generated by Django 6.0.4 on 2026-04-24 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submuscle',
            name='muscle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.musclegroup'),
            preserve_default=False,
        ),
    ]
