# Generated by Django 6.0.4 on 2026-04-24 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_submuscle_muscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submuscle',
            name='muscle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.musclegroup'),
        ),
    ]
