# Generated by Django 6.0.4 on 2026-08-01 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_workout_muscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submuscle',
            name='muscle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muscles', to='api.musclegroup'),
        ),
    ]
