# Generated by Django 6.0.4 on 2026-08-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_submuscle_muscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='image_url',
            field=models.ImageField(upload_to='steps'),
        ),
    ]
