# Generated by Django 6.0.4 on 2026-05-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_submuscle_muscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
