# Generated by Django 6.0.4 on 2026-06-17 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_workout_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='endurance_score',
            field=models.CharField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='hypertrophy_score',
            field=models.CharField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='strength_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('isolated', 'isolated'), ('compound', 'compound')], default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')]),
        ),
    ]
