# Generated by Django 6.0.4 on 2026-06-17 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workout_endurance_score_workout_hypertrophy_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='endurance_score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='hypertrophy_score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
