# Generated by Django 6.0.4 on 2026-08-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_steps_workout_alter_workoutmedia_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutmedia',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
