# Generated by Django 6.0.4 on 2026-08-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_workoutmedia_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutmedia',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
