# Generated by Django 6.0.4 on 2026-06-22 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_workout_endurance_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='difficulty',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
