# Generated by Django 6.0.4 on 2026-08-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_workoutmedia_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutmedia',
            name='url',
        ),
        migrations.AddField(
            model_name='workoutmedia',
            name='g_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
