# Generated by Django 6.0.4 on 2026-08-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_workoutmedia_url_workoutmedia_g_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutmedia',
            name='g_url',
            field=models.FileField(upload_to='work_media'),
        ),
    ]
